
---
title: "metabarcoding with dada2: environment installation"
output: html_notebook
---
# update VM configuration
``` {bash}
sudo apt-get update -y 
sudo apt-get install -y libbz2-dev
sudo apt-get install -y liblzma-dev
```
#package install
Following instruction on https://benjjneb.github.io/dada2/dada-installation.html
```{r package install}
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install(version = '3.11')
BiocManager::install("dada2", version = "3.11")
```

```{r}
BiocManager::install("phangorn") 
```

```{r}
BiocManager::install("DECIPHER")
```

```{r}
install.packages("gridExtra")
```

```{r}
install.packages(.cran_packages)
devtools::install_github(.github_packages)
BiocManager::install(.bioc_packages)
```

```{r}
install.packages("rmarkdown")
```

```{bash}
sudo apt-get install -y libglpk-dev
```

```{r}
BiocManager::install("phyloseq")
```

```{r}
ps <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE), 
               sample_data(samdf), 
               tax_table(taxTab),phy_tree(fitGTR$tree))
ps <- prune_samples(sample_names(ps) != "Mock", ps) # Remove mock sample
ps
```

```{r}
.cran_packages <- c( "shiny","miniUI", "caret", "pls", "e1071", "ggplot2", "randomForest", "dplyr", "ggrepel", "nlme", "devtools",
                  "reshape2", "PMA", "structSSI", "ade4",
                  "ggnetwork", "intergraph", "scales")
.github_packages <- c("jfukuyama/phyloseqGraphTest")
.bioc_packages <- c("genefilter", "impute")
# Install CRAN packages (if not already installed)
.inst <- .cran_packages %in% installed.packages()
if (any(!.inst)){
  install.packages(.cran_packages[!.inst],repos = "http://cran.rstudio.com/")
}
.inst <- .github_packages %in% installed.packages()
if (any(!.inst)){
  devtools::install_github(.github_packages[!.inst])
}

.inst <- .bioc_packages %in% installed.packages()
if(any(!.inst)){
 Biocmanager::install(.bioc_packages[!.inst])
}
```
```{bash}
wget https://cran.r-project.org/src/contrib/Archive/structSSI/structSSI_1.1.1.tar.gz
```
#Hierarchical multiple testing
```{r}
library(devtools)
install_local("./structSSI_1.1.1.tar.gz")
BiocManager::install("DESeq2")
```








